package:

name: crystalmaths

version: 1

source:

git_rev: master

git_url: https://github.com/crystalmaths

requirements:

host:

python
run:

python
test:

imports:

crystalmaths
about:

home: https://github.com/crystalmaths

license: MIT License

license_file: LICENSE